### ISSUE TITLE
Installing GIS Tools for Hadoop

### ISSUE THREAD

**Issue by srdav1s** [Esri/gis-tools-for-hadoop#11]
Do you have any detailed instructions for installing the GIS Tools for Hadoop?   For those of us who are not familiar with building open source projects, the instructions are pretty vague.

Thanks!
Sandy

**Comment by smambrose** [comment]
Hi Sandy,

We have added a [tutorial for beginners](https://github.com/Esri/gis-tools-for-hadoop/wiki/GIS-Tools-for-Hadoop-for-Beginners) - let us know if that helps.
