### ISSUE TITLE
Copy to HDFS not working

### ISSUE THREAD

**Issue by trumboosahil** [Esri/gis-tools-for-hadoop#16]
<b>Here is the error detail!!</B>

![clipboard01](https://cloud.githubusercontent.com/assets/3725274/4897853/29c41724-640a-11e4-9af4-cf7fe03503cf.jpg)

 <p style="color: #0000FF">
        <strong> I have Windows 7 as Host machine and Cloudera VM (Linux) as guest machine. Arcmap is installed on Host machine please find the screen shot below while accessing http://192.168.56.101:50070/ through  browser on the same machine as ArcMap.</strong></p>
![clipboard02](https://cloud.githubusercontent.com/assets/3725274/4897881/9f46552a-640a-11e4-9dfb-066a77ff5b32.jpg)

**Comment by smambrose** [comment]
Check out a step by step tutorial on starting out with GIS tools for hadoop using a sandbox [here.] (https://github.com/Esri/gis-tools-for-hadoop/wiki/GIS-Tools-for-Hadoop-for-Beginners)

When you have worked through those steps you can start moving data between ArcGIS and Hadoop using [this](https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS) and [this](https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-a-Feature-Class-into-HDFS) tutorial.
