### ISSUE TITLE
 Invalid argument in point-in-polygon-aggregation-mr

### ISSUE THREAD

**Issue by trumboosahil** [Esri/gis-tools-for-hadoop#17]
I downloaded code from https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-mr and after building the jar file I run the example and got an error "Invalid argument" because there is a condition if (args.length != 3) when I ouput the args.length it is 6

As a matter of fact I didn't change anything from source code or shell script

**Comment by randallwhitman** [comment]
Idea for workaround (like #18):
```java
int argc = args.length;
int expected = 3;
if (argc > expected && AggregationSampleDriver.class.getName().equals(args[0])) {
	for (int ix=0; ix<expected; ++ix) {
		args[ix] = args[ix+argc-expected];  // shift by argc-expected
	}
	argc = expected;  // pretend
}
```
