### ISSUE TITLE
Torubles installing GeoProcessing Tools in ArcMap

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/gis-tools-for-hadoop#27]
Hi all,
I'm having troubles installing Geoprocessing tools for Hadoop on ArcMap 10.3. I am running Hadoop and Hive on guest Hortonwroks Sandbox 2.1 VM as guest. ArcMap is installed on Windows 8 host machine.

Following instructions given (https://github.com/Esri/geoprocessing-tools-for-hadoop) I get errors on imported python scripts as shown below:
![image002](https://cloud.githubusercontent.com/assets/12309506/7555713/19867da6-f754-11e4-8937-adfa17fa0de8.jpg)

Also, trying to import Sample Model toolbox from point-in-polygon-mr sample (https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-mr/gp) I get a similar error:
![image004](https://cloud.githubusercontent.com/assets/12309506/7555715/1ff701e2-f754-11e4-9650-bdb674c696df.jpg)

Could you, please, help me?
Thanks in advance.

**Comment by climbage** [comment]
@smambrose does this look like anything you've come across?

**Comment by smambrose** [comment]
@pacorodrgz We haven't seen anything like this with 10.3. I'm currently working on reproducing this. Which page did you download the geoprocessing tools from (and where they zipped?)

**Comment by pacorodrgz** [comment]
Sorry... What do you mean by something I've come across for 10.3?

I'm trying to complete point-in-polygon-mr sample and I need to install geoprocessing tools for hadoop in ArcMap and followed instructions:

1 - Download this repository as a .zip file and unzip to a suitable location or clone the repository with a git tool. - Unziped 'geoprocessing-tools-for-hadoop-master.zip' file on C:\esri-gp-sample directory.

2 - WebHDFS and Requests libraries in the tool folder are provided for convenience. If you know you will using libraries installed in /site-packages folder then remove 'webhdfs' or 'requests' folders - otherwise do not. - I don't know, so i do not.

3 - In the ‘ArcToolbox’ pane of ArcGIS Desktop, use the ‘Add Toolbox…’ command to add the Hadoop Tools toolbox (the HadoopTools.pyt file you saved in step 1) file into ArcGIS Desktop. - I start ArcMap 10.3 and proceed as indicated. HadoopTools.pyt file appears on ArcToolbox pane. However, tool python scripts seem to be unavailable as they have a red cross.

4 - Use the tools individually, or use them in models and scripts, such as the examples in: GIS Tools for Hadoop. - Can't use tools.


I tried then to run the SampleModel by downloading and extracting gis-tools-for-hadoop/samples/data/samples.gdb.zip file in C:\esri-gp-sample\ where I've already copied gis-tools-for-hadoop/samples/data/point-in-polygon-aggregation-mr/gp folder. When connencting ArcMap with sample directory there's again a red cross on RunSampleApplication. I did not modified job.properties file.

![arcmap](https://cloud.githubusercontent.com/assets/12309506/7574808/5986b0d8-f830-11e4-97d9-11028225d658.jpg)


I hope you can help me.

Thanks in advance.

**Comment by smambrose** [comment]
@pacorodrgz 

Sorry for the confusion, I just meant the team ate Esri hasn't seen this problem with anyone using ArcMap 10.3 yet and you are the first case.

When you downloaded the zipped file for Hadoop Tools, did you use the "download zip" button this page: https://github.com/Esri/geoprocessing-tools-for-hadoop

or on this one? 

https://github.com/Esri/geoprocessing-tools-for-hadoop/releases

**Comment by pacorodrgz** [comment]
I used the first link.

**Comment by pacorodrgz** [comment]
Editing SampleModel and trying to open Copy from HDFS tool I get the following error:
![error](https://cloud.githubusercontent.com/assets/12309506/7575720/6e074278-f837-11e4-924f-fd25df718997.JPG)

**Comment by smambrose** [comment]
Hi @pacorodrgz,

We've been able to reproduce this error. We have determined that the problem is using the GP tools with localized language packs. We are currently trying to determine the best solution for this.

The best work is to use ArcMap in English for now.  You should be able to change the language settings using the [following steps.](http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#//00030000000q000000.htm)

**Comment by pacorodrgz** [comment]
It worked! Thank you so much!

**Comment by smambrose** [comment]
@pacorodrgz 

If you download the latest version (by completing the previous steps by downloading the zipped file) you will get an updated toolbox that will work with your language pack.
