### ISSUE TITLE
Multipolygon JSON import

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/gis-tools-for-hadoop#29]
I got a JSON file with country boundaries as polygons. Some countries have just one shape (polygon) and other countries have more, like this:

{"type":"Feature","id":"AZE","properties":{"name":"Azerbaijan"},"geometry":{"type":"MultiPolygon","coordinates":[[[[45.001987,39.740004],[45.298145,39.471751],[45.739978,39.473999],[45.735379,39.319719],[46.143623,38.741201],[45.457722,38.874139],[44.952688,39.335765],[44.79399,39.713003],[45.001987,39.740004]]],[[[47.373315,41.219732],[47.815666,41.151416],[47.987283,41.405819],[48.584353,41.80887],[49.110264,41.282287],[49.618915,40.572924],[50.08483,40.526157],[50.392821,40.256561],[49.569202,40.176101],[49.395259,39.399482],[49.223228,39.049219],[48.856532,38.815486],[48.883249,38.320245],[48.634375,38.270378],[48.010744,38.794015],[48.355529,39.288765],[48.060095,39.582235],[47.685079,39.508364],[46.50572,38.770605],[46.483499,39.464155],[46.034534,39.628021],[45.610012,39.899994],[45.891907,40.218476],[45.359175,40.561504],[45.560351,40.81229],[45.179496,40.985354],[44.97248,41.248129],[45.217426,41.411452],[45.962601,41.123873],[46.501637,41.064445],[46.637908,41.181673],[46.145432,41.722802],[46.404951,41.860675],[46.686071,41.827137],[47.373315,41.219732]]]]}},
{"type":"Feature","id":"BDI","properties":{"name":"Burundi"},"geometry":{"type":"Polygon","coordinates":[[[29.339998,-4.499983],[29.276384,-3.293907],[29.024926,-2.839258],[29.632176,-2.917858],[29.938359,-2.348487],[30.469696,-2.413858],[30.527677,-2.807632],[30.743013,-3.034285],[30.752263,-3.35933],[30.50556,-3.568567],[30.116333,-4.090138],[29.753512,-4.452389],[29.339998,-4.499983]]]}},

When creating this table:

CREATE EXTERNAL TABLE boundaries (Id STRING, Name STRING, BoundaryShape binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION '/user/esri/Test/Tables/boundaries';

I get the following error:

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: com.esri.hadoop.hive.serde.JsonSerde.

I want to create a table with Id STRING, Name STRING, BoundaryShape BINARY (which should contain just one polygon) fields. How can I load multipolygon data into this BoundaryShape field?

Thanks in advance.

**Comment by climbage** [comment]
Hi @pacorodrgz, there are a couple of issues here. 

1. Your data is in the [GeoJSON](http://geojson.org/) format, but you are using an input format for Esri's [Enclosed JSON](https://github.com/Esri/spatial-framework-for-hadoop/wiki/JSON-Formats) format.  I don't know of a GeoJSON input format that will work with our functions, but it seems like something we should look at supporting natively (@randallwhitman - what do you think?)  . 
2. The error `Cannot validate serde: com.esri.hadoop.hive.serde.JsonSerde` actually means that Hive can't find the serde class ` com.esri.hadoop.hive.serde.JsonSerde` in the classpath, and is unrelated to the data in the files.  

  In this case you may need to make sure the jars are in the hadoop classpath (not sure why this is). 

      bash> export HADOOP_CLASSPATH=/path/to/spatial-sdk-*.jar

**Comment by randallwhitman** [comment]
Right, the format of your country data is GeoJSON rather than Esri REST JSON.

Options include:
1. Convert the country data before creating the spatial table in Hive;
2. Use [`ST_GeomFromGeoJson(String)`](https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Constructors) on each record separately;
3. Introduce a GeoJsonSerde.

@climbage - it would be good to have GeoJSON SerDe, InputFormat, and RecordReader in the [Spatial Framework for Hadoop](https://github.com/Esri/spatial-framework-for-hadoop).

About not finding JsonSerde in the classpath, there have been issues with Hive v0.11 and v0.12, but if you (@pacordrgz) are using Hortonworks-2.1 I think that has a newer Hive version (in which that issue would be resolved).

**Comment by pacorodrgz** [comment]
Hi,

I came through GeoJSON file format issue by turning a similar KML file into JSON one which looks like the following:

{"displayFieldName":"","fieldAliases":{"OID":"OID","Name":"Name","FolderPath":"FolderPath","SymbolID":"SymbolID","AltMode":"AltMode","Base":"Base","Clamped":"Clamped","Extruded":"Extruded","Snippet":"Snippet","PopupInfo":"PopupInfo","Shape_Length":"Shape_Length","Shape_Area":"Shape_Area"}
,"geometryType":"esriGeometryPolygon","spatialReference":{"wkid":4326,"latestWkid":4326}
,"fields":[{"name":"OID","type":"esriFieldTypeOID","alias":"OID"}
,{"name":"Name","type":"esriFieldTypeString","alias":"Name","length":255}
,{"name":"FolderPath","type":"esriFieldTypeString","alias":"FolderPath","length":255}
,{"name":"SymbolID","type":"esriFieldTypeInteger","alias":"SymbolID"}
,{"name":"AltMode","type":"esriFieldTypeSmallInteger","alias":"AltMode"}
,{"name":"Base","type":"esriFieldTypeDouble","alias":"Base"}
,{"name":"Clamped","type":"esriFieldTypeSmallInteger","alias":"Clamped"}
,{"name":"Extruded","type":"esriFieldTypeSmallInteger","alias":"Extruded"}
,{"name":"Snippet","type":"esriFieldTypeString","alias":"Snippet","length":268435455}
,{"name":"PopupInfo","type":"esriFieldTypeString","alias":"PopupInfo","length":268435455}
,{"name":"Shape_Length","type":"esriFieldTypeDouble","alias":"Shape_Length"}
,{"name":"Shape_Area","type":"esriFieldTypeDouble","alias":"Shape_Area"}
],"features":[
{"attributes":"OID":1,"Name":"Aruba","FolderPath":"Document","SymbolID":0,"AltMode":0,"Base":0,"Clamped":-1,"Extruded":0,"Snippet":"","PopupInfo":"ISO_A2=AW : ISO_N3=533.0","Shape_Length":0.53411148189661473,"Shape_Area":0.01286254999573069}
,"geometry":{"rings":[[[-69.899138759999971,12.452005110000073],[-69.895676439999988,12.423014630000068],[-69.942159389999972,12.438517560000037],[-70.004145269999981,12.500503440000045],[-70.066131149999933,12.546986400000037],[-70.050860769999986,12.597086700000034],[-70.035125289999939,12.614114080000036],[-69.973139409999987,12.567631130000052],[-69.911799489999964,12.480478830000038],[-69.899138759999971,12.452005110000073]]]}
}
...


I created then, Hadoop table by the code below:

CREATE EXTERNAL TABLE countries (Name STRING, BoundaryShape binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION '/user/esri/Test/Tables/countries';


Finally, I ran the following query and returned:

CREATE TABLE earthquakes_new(epicentre binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
INSERT OVERWRITE TABLE earthquakes_new
SELECT ST_Point(longitude, latitude) FROM earthquakes
JOIN countries
WHERE ST_Contains(countries.BoundaryShape, ST_Point(earthquakes.longitude, earthquakes.latitude));
![describe formatted earthquakes_new](https://cloud.githubusercontent.com/assets/12309506/7716385/e16cad06-fe91-11e4-8b24-791f873074c0.JPG)


This is the MapReduce task trace:
![traza mapreduce](https://cloud.githubusercontent.com/assets/12309506/7716435/69c56fda-fe92-11e4-9d9e-5b5b675a8494.JPG)


When importing resulting table into ArcMap I get this "No JSON object could be decoded" error:
![error](https://cloud.githubusercontent.com/assets/12309506/7716471/c15e72c8-fe92-11e4-8a48-a4582a12fea7.JPG)


Could you please help me?

Thanks in advance.

**Comment by randallwhitman** [comment]
It appears that the error comes from processing the [JSON of the webhdfs protocol](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html) - rather than from the content of the `earthquakes_new` output - because it is *Copy From HDFS* and not *JSON To Features* that is in use.

The next question, of course, would be what to do about it.

**Comment by smambrose** [comment]
@pacorodrgz 

do you have a screen shot of the tool before running it (with all the inputs?)

**Comment by randallwhitman** [comment]
GeoJsonInputFormat and GeoJsonSerDe are implemented on spatial-framework-for-hadoop git master.

**Comment by randallwhitman** [comment]
GeoJsonInputFormat and GeoJsonSerDe are included in spatial-framework-for-hadoop v1.2 release.
