### ISSUE TITLE
Enhancement request: magic operators <-> and <#>

### ISSUE THREAD

**Issue by kcavagnolo** [Esri/gis-tools-for-hadoop#31]
I just completed a clunky nearest neighbor implementation using Hive and PySpark for a 1B+ record data set that needs to be queried against a global city lat/lon list. I realized how much cooler it would have been if the <-> and <#> operators were available and my 60 lines of code would become a single query. Any plans for putting these operators in a forthcoming release?

**Comment by climbage** [comment]
Hi @kcavagnolo, what exactly are the `<->` and `<#>` operators?

**Comment by climbage** [comment]
@randallwhitman - for reference : http://boundlessgeo.com/2011/09/indexed-nearest-neighbour-search-in-postgis/

**Comment by climbage** [comment]
We already have a distance function, but of course it will be slow for any type of all pairs neighborhood search.  Doing this efficiently would require altering the query plan and implementing an efficient distributed nearest neighborhood search.

**Comment by kcavagnolo** [comment]
Cleaning up my GH issues and noticed this is still open. Safe to assume it's not going to happen.
