### ISSUE TITLE
look for advice to optimize ST_Intersect

### ISSUE THREAD

**Issue by colin-sgrc** [Esri/gis-tools-for-hadoop#32]
Hi, for a class project I decided to look into this toolset.  The plan was to bring in roads data (OSM and a gov't roads dataset) to the cluster and compare road lengths of each dataset.  I built a fishnet in ArcGIS for my study area, uploaded to the cluster and am intersecting/summing the road distance for each roads dataset.  The goal is to show on a map the areas in the study area that have more/less road distance.

here is my schema in hive:

CREATE TABLE bc_fishnet_05dd (OID string, geom binary)                                         
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

CREATE TABLE bc_osm (osm_id string, type string, geom binary)                                         
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

and here is the query just for OSM:

create temporary function ST_Intersects as 'com.esri.hadoop.hive.ST_Intersects';
create temporary function ST_Intersection as 'com.esri.hadoop.hive.ST_Intersection';
create temporary function ST_SetSRID as 'com.esri.hadoop.hive.ST_SetSRID';
create temporary function ST_GeodesicLengthWGS84 as 'com.esri.hadoop.hive.ST_GeodesicLengthWGS84';

insert overwrite table bc_osm_by_fishnet
select f.oid, sum(ST_GeodesicLengthWGS84(ST_SetSRID(ST_Intersection(f.geom, n.geom), 4326)))
  from bc_fishnet_05dd f, bc_osm n
 where type not in ('rest_area', 'cycleway' ,'footway', 'path', 'pedestrian', 'rest_area', 'steps', 'track', 'trail', 'service')
   and ST_Intersects(n.geom, f.geom)
 group by f.oid;

It takes a substantial amount of time, even when reducing the fishnet polygons to only ones where there are roads (count = 10k).  My OSM count is 150K or so).

So, I guess the question is, is there a way to optimize this?  This isn't really large amounts of data, ArcGIS can handle it fine.  

Hoping to get advice or else my project will be more about evaluation of different spatial tools out there, not the actual results.

Thanks

**Comment by randallwhitman** [comment]
The first ideas that occur to me (without taking much time to evaluate the ideas):

* If you first filter with `ST_EnvIntersects` (note **Env**), does the query run faster or slower?

* Try a custom MapReduce application, adapted from [the sample](https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-mr), that in each Mapper loads the polygons into a just-in-time in-memory quadtree index.

**Comment by colin-sgrc** [comment]
Thanks, I'll tried MapReduce, just found EnclosedJsonInputFormat to use.  But looks like it is  compiled against mapred classes, not mapreduce.  Not sure I want to start recompiling stuff to work with our cluster and whatnot, so I think I'm scrapping this idea.

Thanks again.

**Comment by randallwhitman** [comment]
On spatial-framework-for-hadoop git master, Enclosed JSON InputFormat classes for Esri JSON and GeoJSON now support MapReduce-v2 API (MRv2, `mapreduce` package).
