### ISSUE TITLE
copy from hdfs - json to features

### ISSUE THREAD

**Issue by kc-lee** [Esri/gis-tools-for-hadoop#34]
Hi I created a model as such
![capture](https://cloud.githubusercontent.com/assets/16011826/11427659/b21ba594-949f-11e5-918d-8fede2ce7b96.PNG)

But the output FC is somewhere in the ocean..
![capture2](https://cloud.githubusercontent.com/assets/16011826/11427692/f8f9a6e6-949f-11e5-8960-3825a2521d14.PNG)

Is the issue with the binning? Help!

**Comment by climbage** [comment]
My best guess is that you need to define the projection on your binned output so it gets reprojected correctly to your frames coordinate system.

**Comment by kc-lee** [comment]
yes, thanks. I reprojected it and it looked fine, Thanks!
