### ISSUE TITLE
BinaryTypeInfo Error

### ISSUE THREAD

**Issue by mkeller3** [Esri/gis-tools-for-hadoop#37]
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. binaryTypeInfo

I receive the following error while running the code:

CREATE TABLE mtkellr2.counties (Area string, Perimeter string, State string, County string, Name string, BoundaryShape binary)                                         
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

I am using Hive 0.8.1

**Comment by climbage** [comment]
The issue here is that your version of Hive has a bug related to binary fields.  The GIS tools only support Hive 0.9 and up.
