### ISSUE TITLE
USA state json data file

### ISSUE THREAD

**Issue by noorneo** [Esri/gis-tools-for-hadoop#38]
There is california-counties.json file available, how do I get ESRI USA-state.json file?

**Comment by randallwhitman** [comment]
While the GIS-Tools-for-Hadoop repository contains just enough sample data for the sample code to be self-contained, the repo is not really a data hub.

Maybe someone reading this issue will have an idea where to look.

**Comment by GISDev01** [comment]
You should maybe check out the repo here: https://github.com/project-open-data/esri2open
You can just get the real deal states data straight from the census bureau site as a shapefile and convert it to Json using the above repo. 
Alternatively, you could use the GP tool on arcgis Pro to converts features to Json as well.
