### ISSUE TITLE
clone the github repo: Connection time out

### ISSUE THREAD

**Issue by Toubabmarc** [Esri/gis-tools-for-hadoop#41]
Hello, I try to install the VM but the cloning of the github repo always fails. What must I do?
![hadoopfail](https://cloud.githubusercontent.com/assets/18034328/13991606/25d14e00-f119-11e5-8cbe-784470a26c13.PNG)

Best regards,

Marc

**Comment by randallwhitman** [comment]
Is port 22 filtered by a firewall?
