### ISSUE TITLE
Creating Counties Table

### ISSUE THREAD

**Issue by mkeller3** [Esri/gis-tools-for-hadoop#42]
Hello,

When creating the table for the California counties:

CREATE TABLE counties (Area string, Perimeter string, State string, County string, Name string, BoundaryShape binary)                                         
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

It notes that a column is called BoundaryShape, but when i convert the json file to a feature class it does not have the column so I am trying to figure out where it gets this information from to find the boundaries for each of the polygons.

I am trying to do a similar project with the US States and am trying to figure out what would be the equivalent to the BoundaryShape field.

**Comment by randallwhitman** [comment]
By "when i convert the json file to a feature class",
* do you mean import it to ArcGIS Desktop with the *JSON To Features* tool?
* do you mean custom Java code using  `com.esri.json.EsriFeatureClass#fromJson`?
* do you mean something else?

**Comment by mkeller3** [comment]
Import it to ArcGIS Desktop with the JSON To Features tool

**Comment by randallwhitman** [comment]
ArcGIS Desktop likely calls it "SHAPE" rather than "BoundaryShape".

**Comment by mkeller3** [comment]
If ArcGIS Desktop likely calls it "SHAPE" rather than "BoundaryShape" then for my other file where "Area" is called "Shape_Area" in ArcGIS Desktop would I put "BoundaryShapeArea" inside the create table function for hadoop?

**Comment by randallwhitman** [comment]
ArcGIS desktop automatically generates "Shape_Area" for polygon feature classes.

**Comment by mkeller3** [comment]
So for any json file when creating the table it should be labeled BoundaryShape not Shape_Area?

**Comment by randallwhitman** [comment]
That should work OK.
