### ISSUE TITLE
Error when trying to retrieve date values 

### ISSUE THREAD

**Issue by SrinivasRIL** [Esri/gis-tools-for-hadoop#45]
Hi
I am finding difficulty when it comes to retrieving date values in hive. 
My query is 

 create external table test1(DISPLAYSCALE int, CREATED_DATE date, LAST_EDITED_DATE date)
    > ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'
    > STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedJsonInputFormat'
    > OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

When I try to use the select \* from test1 limit5 I get this error;
Failed with exception java.io.IOException:java.lang.ClassCastException: org.apache.hadoop.hive.serde2.io.DateWritable cannot be cast to org.apache.hadoop.io.Text

As per the json the datatype for  CREATED_DATE and  CREATED_DATE are esriFieldTypeDate and the values are in this format say 2013-11-20 09:39:25.000001.  
So i used the date datatype while creating the table, copied it to HDFS using the unenclosed json and used the select \* query to retrieve the columns, but I get the above error.
To get the values we are creating the same table with string data type respectively instead of date and we are able to get the values .

Can you suggest a solution for this problem. This may seem silly but I am pretty new to programming.

Thanks

**Comment by randallwhitman** [comment]
We may not have ever tested with `esriTypeDate` or with Hive/SQL type `date`.

**Comment by SrinivasRIL** [comment]
It would be great f you can look into it, because we are stuck with this problem for the past few days now and are not able top resolve it. Thanks and appreciate your help

**Comment by randallwhitman** [comment]
Would you be able to paste in 2-3 rows of sample data that illustrate the issue?

**Comment by SrinivasRIL** [comment]
Hi Randall, sorry for the late reply

In the JSON the the data type for created_date and last_edited_date is esriFieldTypeDate as shown in the image (I am using an enclosed json just to show you the datatype mentioned in the json)
![json](https://cloud.githubusercontent.com/assets/18610287/15207499/37292e8c-1844-11e6-971e-25c8c4b578a1.PNG)

I had already created a table but instead of the date datatype i used string and I got the below resullts
![capture1](https://cloud.githubusercontent.com/assets/18610287/15207543/8afec378-1844-11e6-9992-6eeb52b6e590.PNG)

But as mentioned in the original question, when I use the date datatype instead of string while creating the table we are getting the following error after execulting the select query.

> create external table test1( CREATED_DATE date, LAST_EDITED_DATE date)
> ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'
> STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedJsonInputFormat'
> OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
 
Failed with exception java.io.IOException:java.lang.ClassCastException: org.apache.hadoop.hive.serde2.io.DateWritable cannot be cast to org.apache.hadoop.io.Text.

I tried using timestamp as the datatype but to no use. We are migrating all the feature classes having date fields as string datatype only as for now. 
If you need anymore clarifications from me , glad to help.

Thanks

**Comment by randallwhitman** [comment]
For the Esri JSON SerDe, a binary column for geometry is required.
[reference](https://github.com/Esri/spatial-framework-for-hadoop/wiki/Hive-JSON-SerDe)

**Comment by randallwhitman** [comment]
In comment of 2016/05/12, I see metadata, but not sample data.

**Comment by randallwhitman** [comment]
Date and Timestamp columns are now supported in [Spatial Framework for Hadoop v2](https://github.com/Esri/spatial-framework-for-hadoop/releases).
