### ISSUE TITLE
error while creating a json file using hadoop toolbox

### ISSUE THREAD

**Issue by vittal1hbbr** [Esri/gis-tools-for-hadoop#46]
a)I receive error as shown below when i try to create a json file for a feature class. 

Executing: FeaturesToJSON RILGDB.Building D:\hadoop\rilgdbbuilding11.json UNENCLOSED_JSON NOT_FORMATTED
Start Time: Tue May 10 15:27:29 2016
Running script FeaturesToJSON...

Traceback (most recent call last):
  File "<string>", line 365, in execute
  File "D:\GIS tools for hadoop\geoprocessing-tools-for-hadoop-master\geoprocessing-tools-for-hadoop-master\JSONUtil.py", line 413, in ConvertFC2JSONUnenclosed
    attributes_json [field_list[i]] = (attr if type (attr)! = datetime.datetime else unicode (attr))
RuntimeError

Failed to execute (FeaturesToJSON).
Failed at Tue May 10 15:28:45 2016 (Elapsed Time: 1 minutes 16 seconds)

**Comment by GISDev01** [comment]
Can you provide further information on the data here? Some kind of building data? 2d? 3d? Can you copy/paste a record/row from the feature class with field names and types? How many records?

The error indicates an issue in the code at this spot:
https://github.com/Esri/geoprocessing-tools-for-hadoop/blob/master/JSONUtil.py#L413
