### ISSUE TITLE
Job Not Completing

### ISSUE THREAD

**Issue by mkeller3** [Esri/gis-tools-for-hadoop#48]
I am trying to count how many points are within each zip code in the United States and it takes over 21 hours to complete.

If i use a very basic json such as [states](https://www.arcgis.com/home/item.html?id=f7f805eb65eb4ab787a0a3e1116ca7e5) it runs within 3 minutes but anytime i try to use polygons that are far more advance the job takes substantially longer.

Is there any reasoning behind this?

**Comment by randallwhitman** [comment]
Is that in Hive?
For better performance of point-in-polygon aggregation, try a [custom map-reduce application with a quadtree index on the polygons, as in the sample](https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-mr).

**Comment by mkeller3** [comment]
It is in Hive.

**Comment by randallwhitman** [comment]
Right - if the performance of the Hive query is not adequate, try custom MapReduce.

**Comment by mkeller3** [comment]
Randall,

Running the custom MapReduce does not work either. I run into the error:

Error: GC overhead limit exceeded

**Comment by randallwhitman** [comment]
Can you give the JVM more memory?

**Comment by mkeller3** [comment]
That did not help.

**Comment by mkeller3** [comment]
Could this be due to the fact that only one mapper and reducer is being used on such a large polygon dataset?

**Comment by randallwhitman** [comment]
Yes, single mapper and reducer would certainly cause performance and/or scalability issues.

**Comment by mkeller3** [comment]
Is there anyway to force more mappers and reducers to be used?

**Comment by randallwhitman** [comment]
In custom map-reduce, number of reducers, yes.
