### ISSUE TITLE
Computing Area on projection using SRID

### ISSUE THREAD

**Issue by chaosmail** [Esri/gis-tools-for-hadoop#50]
I am wondering how to compute the area of the underlying projection (using SRID) similar to the function `ST_GeodesicLengthWGS84`. Can somebody guide me on how to do this?

Currently I am using this code:

```SQL
SELECT
  ST_Area(ST_GeomFromText(A.area_wkt, 4326)),
  ST_Length(ST_GeomFromText(A.line_wkt, 4326)),
  ST_GeodesicLengthWGS84(ST_GeomFromText(A.line_wkt, 4326))
FROM A
```

Best,
Christoph

**Comment by climbage** [comment]
There is no Hive UDF for calculating the geodesic area at this time, only the geodesic length.  `ST_Area` is planar only.

**Comment by chaosmail** [comment]
Alright, thanks for the quick reply. I was wondering if you would accept a PR on function `ST_GeodesicAreaWGS84` or if you are plannig automatic detection of the projection in the `ST_Area` function (like in ArcGis)?

**Comment by climbage** [comment]
These tools are wrappers around the [Esri Java Geometry API](https://github.com/Esri/geometry-api-java), so support for new operators would depend on that library.  @stolstov, is there a way to calculate area using WGS84 in the geometry library?

**Comment by stolstov** [comment]
Presently the geometry library does not provide geodesic area calculation.

**Comment by climbage** [comment]
@chaosmail we do accept contributions, so a pull request for this functionality would be welcome.

**Comment by chaosmail** [comment]
Alright, I had time now to look a little bit through the code. My approach would be to transform all points of a `com.esri.core.geometry.Geometry` to an area preserving projection and then use the built in `.calculateArea2D()` to compute the area in this projected space. I would put the functionality in the file `com.esri.core.geometry.SpatialReferenceImpl`. Is this the right approach or would you advice something different?

**Comment by chaosmail** [comment]
I think this approach would work for small areas but lead to distortions for large ones. Another way would be approximating the integration on the geoid. However, i am not sure if this iterative approach would be super performant considering that this library is for Hadoop and hence deals with tons of data.

I am quite new to this topic (geodesic operations), so I would need a little guidance.

Thanks a lot!

**Comment by chaosmail** [comment]
I ended up using a Hive Macro to approximate the area in km² of WGS84 geometries.
```
CREATE TEMPORARY MACRO Area(geometry BINARY)
ST_Area(geometry) * pow(pi() / 180 * 6371, 2);
```
The function transforms the area into steradian and then multiplies it with the earth radius squared. For my purpose this is accurate enough.

**Comment by randallwhitman** [comment]
Another approach to approximating geodesic area would be to utilize GeodesicLengthWGS84 somewhat like as done in the Trip-Discovery sample, section "Create grid":
https://blogs.esri.com/esri/arcgis/2013/08/09/vehicle-trip-discovery-with-gis-tools-for-hadoop/#creategrid
