### ISSUE TITLE
Geodesic Length/Area calculations

### ISSUE THREAD

**Issue by butterhc** [Esri/gis-tools-for-hadoop#51]
I wanted to confirm the availability and functionality of the geodesicArea function in the Geometry Engine library.   It seems to point to to a planar2D function which is is throwing off our caculations. 

https://github.com/Esri/gis-tools-for-hadoop/issues/50

This older issue seems to point to the functionality is missing from the library and I didn't see anything that followed up with an update.

The Java API points to it being available.
https://developers.arcgis.com/java/api-reference/index.html?com/esri/core/geometry/GeometryEngine.html
static double geodesicArea(Geometry geometry, SpatialReference spatialReference, AreaUnit areaUnit) 

We also tested the geodesic line functionality against our reference function and it wasn't providing results that matched our reference function.

**Comment by stolstov** [comment]
@butterhc The api link you provided is for the ArcGIS Runtime SDK for Java. It does provide the geodesic area calculation. However, [geometry-api-java](https://github.com/Esri/geometry-api-java/wiki) does not. The only geodesic function available there is geodesicDistanceOnWGS84 for pairs of points.

**Comment by johnrgreiner** [comment]
@stolstov Thank you for responding so quickly.

Yes, we've come to realize that [geometry-api-java](https://github.com/Esri/geometry-api-java/wiki) does not have a class with a geodesicArea() method (through [#50](https://github.com/Esri/gis-tools-for-hadoop/issues/50)).

We are looking to perform various geospatial functions (including calculating the area of geometries in spatial reference WGS84) on our Hadoop stack via Hive and Pig.  Currently we have [spatial-framework-for-hadoop](https://github.com/Esri/spatial-framework-for-hadoop) and [pigeon](https://github.com/aseldawy/pigeon) so we can utilize the geometric-api-java functionality via Hive and Pig respectfully.

Would you know if there is anyway to extend or add to what geometry-api-java offers to include geodesicArea?

**Comment by stolstov** [comment]
@johnrgreiner Could you clarify the question?

> Would you know if there is anyway to extend or add to what geometry-api-java offers to include geodesicArea?

**Comment by johnrgreiner** [comment]
@stolstov Are there other ESRI libraries (i.e. jar files) that we can use in place of esri-geometry-api-1.2.1.jar that provide a greater set of geospatial capabilities (including geodesicArea())?  Can the [ArcGIS Runtime SDK for Java](https://developers.arcgis.com/java/) be used in place of [geometry-api-java](https://github.com/Esri/geometry-api-java/wiki)?

Can other ESRI libraries (i.e. jar files) be used in conjunction with esri-geometry-api-1.2.1.jar to give us the ability to calculate geodesic area?

**Comment by stolstov** [comment]
@randallwhitman @climbage Can you answer these questions?

**Comment by randallwhitman** [comment]
Maybe try asking the question with professional services or sales, rather than developers.
