### ISSUE TITLE
multi-char deserialize error(geojson or esrijson)

### ISSUE THREAD

**Issue by lemonsi** [Esri/gis-tools-for-hadoop#55]
1) data file (utf8 encoding)
![image](https://cloud.githubusercontent.com/assets/26992771/24784801/99b955e4-1b87-11e7-88b7-ea6b9f75371f.png)
2) create table
    ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
    STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
    OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
     or
      ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.GeoJsonSerDe'  
      STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedGeoJsonInputFormat' 
      OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
3) always code error
hive (default)> select County from  u_qqmap.counties limit 1;
OK
?????????

**Comment by randallwhitman** [comment]
Thanks for your report.  If you could provide copy-able text data, that would make it easier to paste to a test case.

**Comment by randallwhitman** [comment]
If you can provide a usable test case let us know.
