### ISSUE TITLE
How can I limit a Hive spatial binning query to a specific map extent?

### ISSUE THREAD

**Issue by mattgray1981** [Esri/gis-tools-for-hadoop#59]
I'm trying to do a HQL query based off a map extent. I cant get this to work, what am I doing wrong? I'm using the taxi_demo in the ESRI example.

SELECT ST_Bin(0.001, ST_Point(dropoff_longitude,dropoff_latitude)) bin_id, *FROM taxi_demo WHERE ST_Contains(ST_Envelope(-8238484.195726455, 4969891.9664984355, -8235431.491909235, 4971962.932233592), ST_Point(dropoff_longitude,dropoff_latitude))

Am I doing something wrong or fat fingering something? It says: No matching method for class com.esri.hadoop.hive.ST_Envelope with (double, double, double, double). Possible choices: FUNC(binary)**
--

![capture](https://user-images.githubusercontent.com/26801360/32449903-6f75e13c-c2d8-11e7-8ae4-05c62033051e.PNG)

**Comment by randallwhitman** [comment]
What versions of Spatial Framework for Hadoop, Geometry, Hive, and Hadoop?

**Comment by mattgray1981** [comment]
Thanks, for the quick response. esri-geometry-api-1.2.1,spatial-sdk-hive-1.1.1, spatial-sdk-json-1.1.1, HDFS 2.7.1.2.3.4.29 , MapReduce2 2.7.1.2.3.4.29 , Hive 1.2.1.2.3.4.29

**Comment by mattgray1981** [comment]
Thanks, for the quick response. esri-geometry-api-1.2.1,spatial-sdk-hive-1.1.1, spatial-sdk-json-1.1.1, HDFS 2.7.1.2.3.4.29 , MapReduce2 2.7.1.2.3.4.29 , Hive 1.2.1.2.3.4.29

**Comment by randallwhitman** [comment]
What happens if you try with Spatial Framework for Hadoop v2.0 (or v1.2), available in the [releases on GitHub](https://github.com/Esri/spatial-framework-for-hadoop/releases)?  (Spatial Framework v2 will also require Geometry v2.)  Also you can try building from source with `maven -Phadoop-2.7 -Phive-1.2 package`.

**Comment by randallwhitman** [comment]
Also what `add jar` statements did you use?

**Comment by mattgray1981** [comment]
add jar hdfs:///sandbox/sandbox21/libs/esri-geometry-api-1.2.1.jar;
add jar hdfs:///sandbox/sandbox21/libs/spatial-sdk-hive-1.1.1-SNAPSHOT.jar;
add jar hdfs:///sandbox/sandbox21/libs/spatial-sdk-json-1.1.1-SNAPSHOT.jar;
add jar hdfs:///sandbox/sandbox21/libs/2017/spatial-sdk-hadoop.jar;

**Comment by mattgray1981** [comment]
add jar hdfs:///sandbox/sandbox21/libs/esri-geometry-api-1.2.1.jar;
add jar hdfs:///sandbox/sandbox21/libs/spatial-sdk-hive-1.1.1-SNAPSHOT.jar;
add jar hdfs:///sandbox/sandbox21/libs/spatial-sdk-json-1.1.1-SNAPSHOT.jar; 
add jar hdfs:///sandbox/sandbox21/libs/2017/spatial-sdk-hadoop.jar;

**Comment by randallwhitman** [comment]
Use `spatial-sdk-hive` and `spatial-sdk-json`, not `spatial-sdk-hadoop`.  (Alternately, use the all-in-one rather than the per-module, but not all 3.)
