### ISSUE TITLE
Error trying to create table with Serde using Enclosed json input format

### ISSUE THREAD

**Issue by psingh30** [Esri/gis-tools-for-hadoop#60]
I am unable to create table "counties" using the command provided in tutorial.

**Command**: CREATE TABLE counties (Area string, Perimeter string, State string, County string, Name string, BoundaryShape binary)                  
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.EsriJsonSerDe'
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedEsriJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

Getting below error when trying the above command.

**FAILED: SemanticException Cannot find class 'com.esri.json.hadoop.EnclosedEsriJsonInputFormat'**

Can you suggest a solution for this issue?

Hive Version:: 1.2.1
Java: 1.8.0_121

**Comment by shivam-dwivedi** [comment]
Jar files does not contain any class file with that name. here is the correct query.

CREATE TABLE counties (Area string, Perimeter string, State string, County string, Name string, BoundaryShape binary)                  
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

**Comment by randallwhitman** [comment]
@shivam-dwivedi Those are the old names, deprecated in v1.2 and will be obsolete in v2.0 of Spatial Framework.
@psingh30 What version do you have?  GitHub releases page has newer than maven central (which is hampered by https://github.com/Esri/spatial-framework-for-hadoop/issues/123).

**Comment by mohammedayub44** [comment]
@psingh30  - Did you happen to find a solution? I'm getting the same error. I'm on "Hive 1.1.0-cdh5.12.2".
@shivam-dwivedi  Those statements did not help.

**Comment by randallwhitman** [comment]
@mohammedayub44  What version of Spatial Framework do you have?
https://github.com/Esri/spatial-framework-for-hadoop/releases

**Comment by cqychen** [comment]
same problem with it 。 
I can create table ,and query 
![image](https://user-images.githubusercontent.com/3394913/51517064-84772e00-1e54-11e9-8b3e-0b132a880049.png)

but can not query counties  alone:
![image](https://user-images.githubusercontent.com/3394913/51517095-a375c000-1e54-11e9-86d2-afca64fce3c7.png)

**Comment by randallwhitman** [comment]
@cqychen   What version of Spatial Framework do you have?
https://github.com/Esri/spatial-framework-for-hadoop/releases

**Comment by randallwhitman** [comment]
So if you followed the sample unchanged, `2.0.0`?  Can you confirm with bytecount or MD5 sum of ` samples/lib/spatial-sdk-hive-2.0.0.jar`?

**Comment by randallwhitman** [comment]
Also, what version of Hive & Hadoop?
Does the workaround of #9 help any?
