### ISSUE TITLE
Taxi_demo table gives garbage output.

### ISSUE THREAD

**Issue by shivam-dwivedi** [Esri/gis-tools-for-hadoop#61]
I am following the spatial binning steps (refer to below link below)
https://github.com/Esri/gis-tools-for-hadoop/wiki/Aggregating-CSV-Data-%28Spatial-Binning%29

when i run the following query it gives me some Garbage output and never finishes, I have to manually interrupt
.FROM (SELECT ST_Bin(0.001, ST_Point(dropoff_longitude,dropoff_latitude)) bin_id, *FROM taxi_demo) bins
SELECT ST_BinEnvelope(0.001, bin_id) shape,
COUNT(*) count
GROUP BY bin_id;

any idea what could be the reason ?

**Comment by randallwhitman** [comment]
How long did you let it run?

**Comment by shivam-dwivedi** [comment]
Heey Randall, I ran the query again with a limit. Please find attached screenshot.
![image](https://user-images.githubusercontent.com/32677492/32852040-ccef1faa-ca5c-11e7-95d3-33e1e5f0955d.png)

**Comment by randallwhitman** [comment]
Image does not suffice for textual data, but I can mention that a Geometry is binary, and will not be human-readable unless wrapped by ST_AsText (or AsJSON, etc.).

**Comment by shivam-dwivedi** [comment]
how would i do that ? would you be able to give an example.

**Comment by randallwhitman** [comment]
examples - https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/test/st-geom-text.sql

**Comment by shivam-dwivedi** [comment]
Thanks so much, I will take a look at it and get back to you, if required :-)
