### ISSUE TITLE
Error in test "point-in-polygon-aggregation-hive" sample

### ISSUE THREAD

**Issue by gislandwu** [Esri/gis-tools-for-hadoop#64]
hello, every one.
my hadoop environment is hadoop2.7.3, hive2.3
and gis tool version include esri-geometry-api-2.0.0.jar, spatial-sdk-hive-2.0.0.jar, spatial-sdk-json-2.0.0.jar
i test "point-in-polygon-aggregation-hive" sample step by step according to run-sample.sql, everything is ok in the process,  but when i run the last sql 

SELECT counties.name, count(*) cnt FROM counties
JOIN earthquakes
WHERE ST_Contains(counties.boundaryshape, ST_Point(earthquakes.longitude, earthquakes.latitude))
GROUP BY counties.name
ORDER BY cnt desc;

i got a error like this:
Exception in thread "main" org.apache.hive.com.esotericsoftware.kryo.KryoException: Unable to find class: com.esri.json.hadoop.EnclosedEsriJsonInputFormat.

an when i run 
select * from counties limit 5;

i also got a error like this:
Exception in thread "main" java.lang.NoSuchMethodError: com.esri.core.geometry.GeometryEngine.jsonToGeometry(Lcom/fasterxml/jackson/core/JsonParser;)Lcom/esri/core/geometry/MapGeometry;

but when i run 
select * from earthquakes limit 5;
it is ok and list the results.

is there anyone give me some suggestion? thanks in advance.

**Comment by randallwhitman** [comment]
What `add jar` statements did you use?

**Comment by gislandwu** [comment]
i add jar like this:
add jar hdfs://master:8020/gis/lib/spatial-sdk-hive-2.0.0.jar;
add jar hdfs://master:8020/gis/lib/spatial-sdk-json-2.0.0.jar;
add jar hdfs://master:8020/gis/lib/esri-geometry-api-2.0.0.jar;

**Comment by randallwhitman** [comment]
What happens if you also `add jar` for the Jackson-v2 jar file?
What happens if you omit the 2 hive configuration statements at the top of step (5)?

**Comment by cucemag** [comment]
i added 
"SET hive.auto.convert.join=false;"
before the select query.
That solves the problem.

**Comment by randallwhitman** [comment]
Thanks for the info.  Was that also with hive v2.3?  @cucemag
