### ISSUE TITLE
esri hive JSON serde not found

### ISSUE THREAD

**Issue by geoHeil** [Esri/gis-tools-for-hadoop#65]
Following along in spark at https://github.com/geoHeil/spatial-heatmaps/tree/master/esri
the JSON serde is not found 
`ClassNotFoundException: Class com.esri.hadoop.hive.serde.JsonSerde not found
`
even though:
```
"com.esri.hadoop" % "spatial-sdk-hive" % esriVersion,
 "com.esri.hadoop" % "spatial-sdk-json" % esriVersion,
```
i.e. the current master branch (2.1.0-SNAPSHOT) are on the class path. Am I missing a dependency? The base JSON Serde would be available but is not called.

**Comment by randallwhitman** [comment]
With Spatial Framework for Hadoop v2, use `EsriJsonSerDe` rather than the obsolete old name `JsonSerde`.

**Comment by geoHeil** [comment]
Thanks.
