### ISSUE TITLE
ST_Contains and ST_Point returns Error Code 1

### ISSUE THREAD

**Issue by Songkorn** [Esri/gis-tools-for-hadoop#71]
Hi all,

I have tested the earthquakes in the counties by using the ST_Contains and ST_Point based on the tutorial. But I have got the return  Error code 1 as following.
===========================================================
hive> SELECT counties.name, count(*) cnt FROM counties
    > JOIN earthquakes
    > WHERE ST_Contains(counties.boundaryshape, ST_Point(earthquakes.longitude, earthquakes.latitude))
    > GROUP BY counties.name
    > ORDER BY cnt desc;
Warning: Map Join MAPJOIN[18][bigTable=earthquakes] in task 'Stage-2:MAPRED' is a cross product
Query ID = cloudera_20180303005050_fa346170-6514-4545-b683-0dbdc8924833
Total jobs = 2
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask
===========================================================

Could you please suggest how to solve this problem?

Regards,
Songkorn

**Comment by Songkorn** [comment]
It works after applying this setting:
SET hive.auto.convert.join=false;

Does anyone can explain it to me?

**Comment by Songkorn** [comment]
It works after add the setting command as below. Does anyone tell me why?

hive> SET hive.auto.convert.join=false;
hive> select c.name, count(*) cnt from counties c, earthquakes e where ST_Contains(c.boundaryshape, ST_Point(e.longitude,e.latitude)) group by c.name order by cnt desc;
Warning: Shuffle Join JOIN[4][tables = [c, e]] in Stage 'Stage-1:MAPRED' is a cross product
Query ID = cloudera_20180303234141_b502848e-4faa-422f-8be7-1e4c4f16d419
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1519778648254_0010, Tracking URL = http://quickstart.cloudera:8088/proxy/application_1519778648254_0010/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1519778648254_0010
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 1
2018-03-03 23:42:21,351 Stage-1 map = 0%,  reduce = 0%
2018-03-03 23:43:21,817 Stage-1 map = 0%,  reduce = 0%
2018-03-03 23:43:26,893 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 66.28 sec
2018-03-03 23:43:55,905 Stage-1 map = 100%,  reduce = 85%, Cumulative CPU 74.88 sec
2018-03-03 23:43:59,306 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 76.81 sec
MapReduce Total cumulative CPU time: 1 minutes 16 seconds 810 msec
Ended Job = job_1519778648254_0010
Launching Job 2 out of 3
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1519778648254_0011, Tracking URL = http://quickstart.cloudera:8088/proxy/application_1519778648254_0011/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1519778648254_0011
Hadoop job information for Stage-2: number of mappers: 1; number of reducers: 1
2018-03-03 23:44:50,437 Stage-2 map = 0%,  reduce = 0%
2018-03-03 23:45:15,437 Stage-2 map = 100%,  reduce = 0%, Cumulative CPU 1.94 sec
2018-03-03 23:45:38,906 Stage-2 map = 100%,  reduce = 100%, Cumulative CPU 4.59 sec
MapReduce Total cumulative CPU time: 4 seconds 590 msec
Ended Job = job_1519778648254_0011
Launching Job 3 out of 3
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1519778648254_0012, Tracking URL = http://quickstart.cloudera:8088/proxy/application_1519778648254_0012/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1519778648254_0012
Hadoop job information for Stage-3: number of mappers: 1; number of reducers: 1
2018-03-03 23:45:58,605 Stage-3 map = 0%,  reduce = 0%
2018-03-03 23:46:20,963 Stage-3 map = 100%,  reduce = 0%, Cumulative CPU 2.23 sec
2018-03-03 23:46:42,057 Stage-3 map = 100%,  reduce = 100%, Cumulative CPU 5.21 sec
MapReduce Total cumulative CPU time: 5 seconds 210 msec
Ended Job = job_1519778648254_0012
MapReduce Jobs Launched: 
Stage-Stage-1: Map: 2  Reduce: 1   Cumulative CPU: 76.81 sec   HDFS Read: 6784744 HDFS Write: 541 SUCCESS
Stage-Stage-2: Map: 1  Reduce: 1   Cumulative CPU: 4.59 sec   HDFS Read: 4546 HDFS Write: 541 SUCCESS
Stage-Stage-3: Map: 1  Reduce: 1   Cumulative CPU: 5.21 sec   HDFS Read: 5452 HDFS Write: 199 SUCCESS
Total MapReduce CPU Time Spent: 1 minutes 26 seconds 610 msec
OK
Kern	36
San Bernardino	35
Imperial	28
Inyo	20
Los Angeles	18
Riverside	14
Monterey	14
Santa Clara	12
Fresno	11
San Benito	11
San Diego	7
Santa Cruz	5
San Luis Obispo	3
Ventura	3
Orange	2
San Mateo	1
Time taken: 286.147 seconds, Fetched: 16 row(s)
hive>

**Comment by climbage** [comment]
Hive has a few different join strategies that have different performance characteristics dependent on data size. In your first case it is choosing the wrong strategy (map-join) because it thinks that it can fit an entire dataset in memory. When you disable this strategy choice optimization, it will default to a shuffle join. Shuffle join (or reduce-join) scales better but generally performs worse for smaller datasets.

Here is some more info on the two join strategies. https://stackoverflow.com/questions/29734690/how-to-decide-when-to-use-a-map-side-join-or-reduce-side-while-writing-an-mr-cod

**Comment by Songkorn** [comment]
Thank you very much for your answer, climbage. I will take a look at the link you provide.

Songkorn
