### ISSUE TITLE
Hive not launching mapreduce jobs.. getting stuck in the middle of execution

### ISSUE THREAD

**Issue by prateekparasher** [Esri/gis-tools-for-hadoop#72]
![mr job stuck](https://user-images.githubusercontent.com/12997990/37677833-15d1b9f2-2c74-11e8-9192-9c60762a38b1.PNG)

**Comment by randallwhitman** [comment]
Hi - thanks for filing an issue.  Image without text makes it hard to read and even harder to copy-paste a query.

**Comment by prateekparasher** [comment]
@randallwhitman  i
![mr job stuck](https://user-images.githubusercontent.com/12997990/37681859-c71490ee-2c7f-11e8-9323-0c16b33632bd.PNG)

https://user-images.githubusercontent.com/12997990/37681859-c71490ee-2c7f-11e8-9323-0c16b33632bd.PNG
