### ISSUE TITLE
Is 3D supported?

### ISSUE THREAD

**Issue by mroecke** [Esri/gis-tools-for-hadoop#77]
All examples are written for 2D. Trying with own 3D data was not working.
Could it be, that 3D geometries are not fully supported?

**Comment by alocke** [comment]
Could you give us some more details? Which operations are you trying with 3D data?

**Comment by git-aybo** [comment]
select esri.ST_PolyFromWKB(esri.ST_AsBinary(esri.ST_GeomFromText('polygon ((0 0, 10 0, 0 10, 0 0))')));  -- 2d works --> returns a bytestring
select esri.ST_PolyFromWKB(esri.ST_AsBinary(esri.ST_GeomFromText('polygon ((0 0 1, 10 0 2, 0 10 3, 0 0 4))')))  -- 3d doesn't work --> returns NULL

**Comment by stolstov** [comment]
@git-aybo Does this work?
`select esri.ST_GeomFromText('polygon z ((0 0 1, 10 0 2, 0 10 3, 0 0 4))') `

**Comment by git-aybo** [comment]
It works now fine, also with m and zm. Thank you for the quick solution .
