### ISSUE TITLE
Connection attempt failed in "Copy FROM HDFS" tool

### ISSUE THREAD

**Issue by TayyabMir56** [Esri/gis-tools-for-hadoop#78]
Hi

I am following the following tutorial: [Move Data from Hive -> ArcGIS](https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS)

I have added the counties and earthquake data and created the agg_samp table from it as instructed and I can query it in the hive as well.

using the descibe command, I can see that my datanode is sandbox-hdp.hortonworks.com
![image](https://user-images.githubusercontent.com/6566554/42377231-e96133a8-813b-11e8-833b-efc2473b9b67.png)

I have added this in the hosts file as well so I can access the HDFS as well as Ambari from the web portal 

![image](https://user-images.githubusercontent.com/6566554/42377340-686652c8-813c-11e8-8f85-72259a315f15.png)

But when I try using the "Copy from HDFS" tool in the GIS Tools for Hadoop Toolbox:

![image](https://user-images.githubusercontent.com/6566554/42377463-d8cbbef4-813c-11e8-846b-fc0bca526b78.png)

I get the following connection error.

![image](https://user-images.githubusercontent.com/6566554/42377572-3a102740-813d-11e8-9879-abdbe7bf3521.png)

Now the thing that I cannot understand is that if I can access the same machine with the web portal, Why does the connection not respond when I do it from ArcGIS.

Note: I have tried using my IP instead of the full name, It gives the same result.
Note 2: I have also tried to ping sandbox-hdp.hortonworks.com and it also times out

![image](https://user-images.githubusercontent.com/6566554/42377698-ceaa8968-813d-11e8-98d1-8b686e4108eb.png)

Please tell me what am I doing wrong here.

Best regards
Tayyab

**Comment by randallwhitman** [comment]
Is there a firewall?

**Comment by randallwhitman** [comment]
If the ping times out, my first guess is there is an issue with the network, rather than an issue perse with GIS Tools for Hadoop.

**Comment by TayyabMir56** [comment]
I solved the issue by opening access to all ports (0 to 65535) on my HDP Server.
Apparently ArcGIS was using a port other than 80 as well, which i could not identify which one exactly.
I know this is a bad practice but oh well. Works for me for now :)

**Comment by climbage** [comment]
@TayyabMir56 the port is most likely `50070` which is configurable in the GP tool. Glad you got it sorted.

**Comment by TayyabMir56** [comment]
@climbage No sir 50070 was already open. Its some other.
